= sloth-protocol - Open Source IM protocol
Andrey Antukh, <niwi@niwi.be>
:toc: left
:numbered:
:icons: font
:source-highlighter: highlightjs
:sectlinks:
:stylesheet: styles.css
:imagesdir: ./images
:iconsdir: ./images

Open Source IM protocol highly inspired by xmpp and hangout.

== Introduction

TODO


== Rationale

TODO


== Addressing Scheme

An entity is anything that can be considered a network endpoint and that can communicate using sloth
protocol. All such entities are uniquelly adressable using URI format.

This is a valid list of possible entity identifiers:

* `sloth://username@domain.com`
* `username@domain.com`

An entity (like in smtp protocol) belongs to one domain / domain provider. Different domains can
hold entities with same node identifier. The node identifier is a string placed before the domain
identifier and separated from the latter by the `@`.

== Transport

=== Overview

The protocol is based complely in asynchronous message based communication. And it has special
focus on *WebSockets* as default and recommended transport protocol. Any other protocol that fulfill
the same or similar semantics is algo a good candidade for transport protocol.

The intention of sloth protocol is to be completely web ready, therefore the decision of use
*WebSockets* as default and recommended transport protocol. But in other environments with full
support for tcp connectivity *zeromq* and/or *nanomsg* would be a great alternative.

=== Messages Stream

The message is consists in a simple key value structure. The sloth protocol has one mandatory format:
*json*. But other formats should also to be supported and used with content negotiation.

.A list of a recommeded formats that sloth compliant serves can implement.
[options="header", cols="1,1,3"]
|=======================================
| Name    | Observations | Link
| json    | Mandatory    | http://www.ietf.org/rfc/rfc4627.txt
| msgpack | Recommended  | http://msgpack.org/
|=======================================

=== Content Negotiation

As, *WebSockets* is a default transport protocol, this section will explain a negotiation of message
format using it as example.

The negotiation of message format is carried out using query params part of websockets uri. This is
a commonly known websocket format uris:

* `ws://domain.com/resource?param=value`
* `wss://domain.com/resource?param=value`

The message format should be provided using `format` parameter on the websocket uri:

* `ws//sloth.land/?format=msgpack`

In case of server does not supports that format, it should close the connection inmediatelly and
may send a message in a *json* format (the unique mandatory format).

=== Connection initialization

This is a simple diagram on how connection is established, and which messages are mandatory
on that process.

1. Create a new connection (server not sends nothing at this moment).
2. Send a authentication message.
3. Server responds with an message notifying if authentication has been successful or failed.
4. In case of successful, client should sent its first status message.

Additional notes:

* Server can close the connection after arbitrary number of failed attempts of authentication
  messages.

=== Message types

An message consists in a simple structure like hash map, mainly without neesting. It has keys
as string and values as string, number or list.

.Example of basic structure of an message.
[source, json]
----
{
  "_type": "message:chat",
  "_id": "b0e59238-494c-41d5-b2c7-47af3872010b",
  "some": "thing"
}
----

The two mandatory entries are *_type* and *_id*. The type represents a message type in format
`<type>:<subtype>[<subsubtype>]` and *_id* is a arbitrary unique identifier that serves for track
the messages (very useful for *iq* messages).

All entries that starts with *_* are reserved by sloth protocol or by its extensions.

==== Message

This is a type of message that a client can send or receive from server. Its purpose is transport
arbitrary im messages.

==== IQ (Info/Query)

Is a request response mechanism that works like http.


== Authentication

The authentication process of sloth protocol consist in very simple credential verification.

.Example of authentication packet request.
[source, json]
----
{
  "username": "username",
  "password": "password",
  "domain": "sloth.land",
  "_type": "iq:put:auth",
  "_id": "b0e59238-494c-41d5-b2c7-47af3872010b",
}
----

.Example of authentication packet successful response.
[source, json]
----
{
  "_status": "success",
  "_type": "iq:put:result",
  "_id": "b0e59238-494c-41d5-b2c7-47af3872010b",
}
----


.Example of authentication packet failed response.
[source, json]
----
{
  "_status": "error",
  "_message": "Username, password or domain may be wrong.",
  "_code": "001",
  "_type": "iq:result:auth",
  "_id": "b0e59238-494c-41d5-b2c7-47af3872010b",
}
----


== Rooms

This is a basic primitive of communication of sloth protocol. Unlike xmpp, sloth does not has
explicit individual/private messages. Every communication will be done in a room.

A room allows two or more person interchange messages.

=== Create room

For start a chat with someone you first need create a room. It should be done with *iq* message type.
Let see an example:

[source,json]
----
{
  "_type": "iq:create:room",
  "_id": "b0e59238-494c-41d5-b2c7-47af3872010b",
  "name": "myroom",
  "participants": [
    "person1@sloth.land",
    "person2@sloth.land"
  ]
}
----

TIP: the domain part can be ommited and it is automatically resolved to current domain.

This request has two possible responses: *success* and *fail*.

TODO: responses examples


=== List rooms

You can request a list rooms to server. The server will return a list of owned rooms
and rooms where you are participating:

[source,json]
----
{
  "_type": "iq:info:room",
  "_id": "b0e59238-494c-41d5-b2c7-47af3872010b",
}
----

This reques will return a response like this:

[source,json]
----
{
  "_type": "iq:info:result",
  "_id": "b0e59238-494c-41d5-b2c7-47af3872010b",
  "_status": "success",
  "rooms": [
    {
       "id": "b0e59238-494c-41d5-b2c7-47af3872011b",
       "name": "foo",
       "created_at": "2015-01-25T01:45:48.428Z",
       "modified_at": "2015-01-25T01:45:48.428Z",
    },
    {
       "id": "b0e59238-494c-41d5-b2c7-47af3872012b",
       "name": "bar",
       "created_at": "2015-01-25T01:45:48.428Z",
       "modified_at": "2015-01-25T01:45:48.428Z",
    }
  ]
}
----

=== Room information

Is an IQ request for obtain a detailled information about one concrete room. It is a way for obtain
a initial state of participants.

.Example of request room information
[source,json]
----
{
  "_type": "iq:info:room",
  "_id": "b0e59238-494c-41d5-b2c7-47af3872010b",
  "id": "b0e59238-494c-41d5-b2c7-47af3872012b",
}
----

.Example of successful
[source,json]
----
{
  "_type": "iq:info:result",
  "_id": "b0e59238-494c-41d5-b2c7-47af3872010b",
  "_status": "success",
  "name": "foo",
  "created_at": "2015-01-25T01:45:48.428Z",
  "modified_at": "2015-01-25T01:45:48.428Z",
  "owner": "person1@sloth.land",
  "participants": [
    {
      "id": "person1@sloth.land",
      "state": "available",
      "state_message": "",
      "last_update": "2015-01-25T01:45:48.428Z",
    },
    {
      "id": "person2@sloth.land",
      "state": "notavailable",
      "state_message": "",
      "last_update": "2015-01-25T01:45:48.428Z",
    }
  ]
}
----
